### ISSUE TITLE
Support changing tokenizer for fields

### ISSUE THREAD

**Issue by lberezy** [kardeiz/pallet#6]
My current use case needs some fields to use a different type of `tantivy::tokenizer`, for example the [`raw`](https://docs.rs/tantivy/0.14.0/tantivy/tokenizer/index.html#raw) kind which is useful for indexing URLs and other things that require exact matching.

I was wondering if there was a way to achieve this in pallet currently (perhaps with `index_field_options` struct field attribute), or if there will be a change required?

**Comment by kardeiz** [comment]
@lberezy Yes, you should be able to do something like this:

```rust
#[pallet(default_search_field, index_field_options="Book::title_opts()")]
```

Where `title_opts` is a function that returns `tantivy::schema::TextOptions`.

**Comment by lberezy** [comment]
Thanks for your response and fantastic timing, I just worked this out as you responded (using `tantivy::schema::STRING` covered what I needed).
